import "@/style/globals.css";
import { satoshi } from "@/lib/font";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={satoshi.className}
            >
                {children}
            </body>
        </html>
    );
}
